POST http://localhost:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"username": "", "password":  "Verca"}


###

POST http://localhost:8080/projects
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "My Project2",
  "contributorsIds": [3,45],
  "description": "Tento projekt je fakt uzasny :) Mam rad JAVU (ne)"
}


###

GET http://localhost:8080/user/3/projects
Accept: application/json


